#:schema node_modules/wrangler/config-schema.json
name = "zhuanhuan"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "732696ff22af4f3e8b38f5afc0e0c057" }
]
